const properties = [
  {
    id: 1,
    title: "Modern Apartment in Mumbai",
    location: "Mumbai",
    price: 8500000,
    type: "Apartment",
    bedrooms: 2,
    bathrooms: 2,
    area: "950 sqft",
    image: "https://picsum.photos/id/1018/500/300",
    tags: ["city view", "near metro", "furnished"],
  },
  {
    id: 2,
    title: "Luxury Villa in Hyderabad",
    location: "Hyderabad",
    price: 22500000,
    type: "Villa",
    bedrooms: 4,
    bathrooms: 4,
    area: "3200 sqft",
    image: "https://picsum.photos/id/1025/500/300",
    tags: ["private garden", "gated society", "garage"],
  },
  {
    id: 3,
    title: "Cozy Studio in Pune",
    location: "Pune",
    price: 4000000,
    type: "Studio",
    bedrooms: 1,
    bathrooms: 1,
    area: "450 sqft",
    image: "https://picsum.photos/id/1043/500/300",
    tags: ["affordable", "single person", "compact"],
  },
  {
    id: 4,
    title: "3BHK Independent House in Bangalore",
    location: "Bangalore",
    price: 13000000,
    type: "Independent House",
    bedrooms: 3,
    bathrooms: 3,
    area: "1800 sqft",
    image: "https://picsum.photos/id/1050/500/300",
    tags: ["corner plot", "parking", "near school"],
  },
  {
    id: 5,
    title: "Smart Apartment in Delhi",
    location: "Delhi",
    price: 9000000,
    type: "Apartment",
    bedrooms: 3,
    bathrooms: 2,
    area: "1200 sqft",
    image: "https://picsum.photos/id/1062/500/300",
    tags: ["smart home", "balcony", "lift access"],
  },
];

export default properties;
